config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:show, :index]
  resources :posts, only: [:index]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :skip => [:registrations]

  get 'welcome/index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # Validations
  validates :title, presence: true
  validates :content, presence: true

  # Relations
  has_one_attached :image
end

app/models/project.rb
class Project < ApplicationRecord
  # Validations
  validates :title, presence: true
  validates :content, presence: true

  # Relations
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require "rss"
  require "open-uri"

  def index
    Analytics.page(
      user_id: "anonymous_id",
      name: 'Posts'
    )
    @posts = medium_news
  end

  private

  def medium_news
    rss = RSS::Parser.parse(open("https://medium.com/feed/@haagwee/").read, false).items[0..6]
    rss.map { |article|
      {
        title: article.title,
        date: article.pubDate,
        link: article.link,
        description: article.description,
        creator: article.dc_creator
      }
    }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show]

  def index
    Analytics.page(
      user_id: "anonymous_id",
      name: 'Projects'
    )
    @projects = Project.all
  end

  def show
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    Analytics.page(
      user_id: "anonymous_id",
      name: 'Home'
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="Haagweee">
<meta name="application-name" content="Haagweee">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/application/_footer.html.slim
footer.footer
  .container.has-text-centered
    .columns
      .column.is-half
        p
          strong One-time
          | donation
        div
          = link_to "bunq", "https://bunq.me/dunya", class: "button", target: :_blank
      .column.is-half
        p
          strong Monthly
          | donation
        div
          = link_to "GitHub", "https://github.com/users/dunyakirkali/sponsorship", class: "button", target: :_blank

app/views/application/_navbar.html.slim
nav.navbar
  .navbar-brand
    = link_to root_path, class: "navbar-item"
      = image_tag("website_logo_transparent_background.png")

    a.navbar-burger.burger role="button" aria-label="menu" aria-expanded="false"
      span aria-hidden="true"
      span aria-hidden="true"
      span aria-hidden="true"

  .navbar-menu
    .navbar-start
      = link_to "Haagwee", root_path, class: "navbar-item"
    .navbar-end
      = active_link_to "Home", root_path, class: "navbar-item", class_active: "is-active", active: :exclusive
      = active_link_to "Projects", projects_path, class: "navbar-item", class_active: "is-active"
      = active_link_to "Blog", posts_path, class: "navbar-item", class_active: "is-active"

app/views/layouts/application.html.slim
doctype html
html
  head
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css'
    = javascript_include_tag 'application'
    = render 'application/favicon'
    script defer=true src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta charset="utf-8"
    title Haagwee
  body
    .columns.is-centered
      .column.is-12-mobile.is-10-tablet.is-6-desktop
        p.notice= notice
        p.alert= alert
        = render "navbar"
        = yield
        = render "footer"

app/views/posts/index.html.slim
section.section
  .content.is-medium
    h1.title Blog
    ul
      - @posts.each do |post|
        li
          p
            span= l(post[:date], format: :short)
            = link_to post[:title], post[:link]
      li
        p
          = link_to "...", "https://medium.com/@haagwee", target: "_blank"

app/views/projects/index.html.slim
section.section
  h1.title Projects
  .columns.is-multiline
    - @projects.each do |project|
      .column.is-12-mobile.is-6-tablet.is-3-desktop
        .card.is-shadowless.is-slightly-rounded
          .card-image
            figure.image
              = link_to project_path(project) do
                = image_tag project.image.variant(combine_options: {resize: '256x256^', extent: '256x256', gravity: 'Center'})
          .card-content
            .content
              p
                span.title.is-4.is-capitalized
                  = link_to project.title, project_path(project)
                br
                span= l(project.created_at, format: :short)

app/views/projects/show.html.slim
section.hero.is-primary
  .hero-body
    .container
      h1.title= @project.title
section
  .container
    == @project.content

app/views/welcome/index.html.slim
section.section
  .content.is-medium
    h1.title Haagwee
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id magna non felis gravida vulputate. Quisque in elit non enim vulputate pellentesque vel ac tortor. Nullam in sem eu purus porttitor lobortis. Nullam id suscipit diam. Quisque pretium, arcu a condimentum interdum, dolor orci consequat nibh, non aliquam diam libero efficitur leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed venenatis ullamcorper diam, vitae venenatis leo iaculis at. Aenean eu mattis ligula, et elementum nulla. Maecenas luctus sapien vitae mauris tincidunt rutrum. Cras ac mi vulputate, tempus purus at, condimentum mi. Aenean tempor, dolor eu bibendum finibus, felis lectus commodo tortor, eget maximus diam sapien vitae metus. In quam nibh, condimentum quis eros quis, sollicitudin eleifend neque.
  .columns
    .column
      article.media
        figure.media-left
          span.icon
            = fa_icon "twitter"
        .media-content
          .content
            = link_to "Twitter", "https://twitter.com/Haagwee1"
    .column
      article.media
        figure.media-left
          span.icon
            = fa_icon "github"
        .media-content
          .content
            = link_to "GitHub", "https://github.com/haagwee"
    .column
      article.media
        figure.media-left
          span.icon
            = fa_icon "linkedin"
        .media-content
          .content
            = link_to "LinkedIn", "https://www.linkedin.com/company/haagwee"
    .column
      article.media
        figure.media-left
          span.icon
            = fa_icon "envelope"
        .media-content
          .content
            = link_to "Email", "https://github.com/haagwee"
  .content
    p
      | Leliestraat 40
      br
      | 2313BH
      br
      | Leiden
      br
      | KVK 773 89 875
      br
      | NL 0031 89 130 B09